[2018-01-07 20:32:26] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:32:26] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:32:27] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:32:27] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:32:27] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:32:27] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:32:27] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:32:27] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:32:28] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:32:28] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:32:28] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:32:28] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:32:28] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:32:28] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:33:21] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:33:21] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:33:22] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:33:22] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:33:22] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:33:22] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:33:22] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:33:22] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:33:22] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:33:22] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:33:22] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:33:22] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:33:26] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-07 20:33:26] application.ERROR: No route found for "GET /api/v1/" [] []
[2018-01-07 20:33:26] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-07 20:33:33] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-07 20:33:33] application.ERROR: No route found for "GET /api/" [] []
[2018-01-07 20:33:33] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-07 20:33:36] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-07 20:33:36] application.ERROR: No route found for "GET /" [] []
[2018-01-07 20:33:36] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-07 20:36:27] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-07 20:36:27] application.ERROR: No route found for "GET /" [] []
[2018-01-07 20:36:27] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-07 20:36:27] application.DEBUG: < 404 [] []
[2018-01-07 20:36:52] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:36:52] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:36:52] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-07 20:36:52] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-07 20:36:52] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-07 20:36:52] application.DEBUG: < 500 [] []
[2018-01-07 20:37:20] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/subjec" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/subjec\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/subjec\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-07 20:37:20] application.ERROR: No route found for "GET /api/v1/subjec" [] []
[2018-01-07 20:37:20] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-07 20:37:20] application.DEBUG: < 404 [] []
[2018-01-07 20:37:27] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 20:37:27] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 20:37:27] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-07 20:37:27] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-07 20:37:27] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-07 20:37:27] application.DEBUG: < 500 [] []
[2018-01-07 20:43:03] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics","route_parameters":{"_controller":"topics.controller:getAll","_route":"GET_api_v1_topics"},"request_uri":"http://localhost:9001/api/v1/topics","method":"GET"} []
[2018-01-07 20:43:03] application.DEBUG: > GET /api/v1/topics [] []
[2018-01-07 20:43:03] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-07 20:43:03] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-07 20:43:03] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/TopicsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/TopicsController.php(23): App\Controllers\TopicsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\TopicsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-07 20:43:03] application.DEBUG: < 500 [] []
[2018-01-07 20:43:16] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/students" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/students\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/students\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-07 20:43:16] application.ERROR: No route found for "GET /api/v1/students" [] []
[2018-01-07 20:43:16] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-07 20:43:16] application.DEBUG: < 404 [] []
[2018-01-07 20:43:28] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "GET /api/v1/users": Method Not Allowed (Allow: POST, OPTIONS) (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /api/v1/users\": Method Not Allowed (Allow: POST, OPTIONS) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2018-01-07 20:43:28] application.ERROR: No route found for "GET /api/v1/users": Method Not Allowed (Allow: POST, OPTIONS) [] []
[2018-01-07 20:43:28] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-07 20:43:28] application.DEBUG: < 405 [] []
[2018-01-07 20:43:35] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/users/id" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/users/id\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/users/id\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-07 20:43:35] application.ERROR: No route found for "GET /api/v1/users/id" [] []
[2018-01-07 20:43:35] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-07 20:43:35] application.DEBUG: < 404 [] []
[2018-01-07 20:43:38] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/users/1" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/users/1\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/users/1\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-07 20:43:38] application.ERROR: No route found for "GET /api/v1/users/1" [] []
[2018-01-07 20:43:38] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-07 20:43:38] application.DEBUG: < 404 [] []
[2018-01-07 20:43:54] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems","route_parameters":{"_controller":"problems.controller:getAll","_route":"GET_api_v1_problems"},"request_uri":"http://localhost:9001/api/v1/problems","method":"GET"} []
[2018-01-07 20:43:54] application.DEBUG: > GET /api/v1/problems [] []
[2018-01-07 20:43:54] application.DEBUG: < 200 [] []
[2018-01-07 22:08:28] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 22:08:28] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 22:08:28] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-07 22:08:28] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-07 22:08:28] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-07 22:08:28] application.DEBUG: < 500 [] []
[2018-01-07 22:08:35] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 22:08:35] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 22:08:35] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-07 22:08:35] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-07 22:08:35] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-07 22:08:35] application.DEBUG: < 500 [] []
[2018-01-07 22:08:36] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 22:08:36] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 22:08:36] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-07 22:08:36] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-07 22:08:36] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-07 22:08:36] application.DEBUG: < 500 [] []
[2018-01-07 22:08:37] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 22:08:37] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 22:08:37] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-07 22:08:37] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-07 22:08:37] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-07 22:08:37] application.DEBUG: < 500 [] []
[2018-01-07 22:08:37] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-07 22:08:37] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-07 22:08:37] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-07 22:08:37] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-07 22:08:37] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-07 22:08:37] application.DEBUG: < 500 [] []
