[2018-01-10 17:56:04] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 17:56:04] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 17:56:04] application.DEBUG: < 200 [] []
[2018-01-10 17:57:09] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 17:57:09] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 17:57:09] application.CRITICAL: LogicException: The controller must return a response (Array(0 => Array(1 => 1, problem_id => 1, 0 => 0), 1 => Array(1 => 1, problem_id => 2, 0 => 0), 2 => Array(1 => 1, problem_id => 3, 0 => 0), 3 => Array(1 => 1, problem_id => 4, 0 => 0), 4 => Array(1 => 1, problem_id => 5, 0 => 0), 5 => Array(1 => 1, problem_id => 6, 0 => 0), 6 => Array(1 => 1, problem_id => 7, 0 => 0), 7 => Array(1 => 1, problem_id => 8, 0 => 0), 8 => Array(1 => 1, problem_id => 9, 0 => 0), 9 => Array(1 => 1, problem_id => 10, 0 => 0)) given). (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/HttpKernel.php line 169 {"exception":"[object] (LogicException(code: 0): The controller must return a response (Array(0 => Array(1 => 1, problem_id => 1, 0 => 0), 1 => Array(1 => 1, problem_id => 2, 0 => 0), 2 => Array(1 => 1, problem_id => 3, 0 => 0), 3 => Array(1 => 1, problem_id => 4, 0 => 0), 4 => Array(1 => 1, problem_id => 5, 0 => 0), 5 => Array(1 => 1, problem_id => 6, 0 => 0), 6 => Array(1 => 1, problem_id => 7, 0 => 0), 7 => Array(1 => 1, problem_id => 8, 0 => 0), 8 => Array(1 => 1, problem_id => 9, 0 => 0), 9 => Array(1 => 1, problem_id => 10, 0 => 0)) given). at /var/www/html/vendor/symfony/http-kernel/HttpKernel.php:169)"} []
[2018-01-10 17:57:09] application.ERROR: The controller must return a response (Array(0 => Array(1 => 1, problem_id => 1, 0 => 0), 1 => Array(1 => 1, problem_id => 2, 0 => 0), 2 => Array(1 => 1, problem_id => 3, 0 => 0), 3 => Array(1 => 1, problem_id => 4, 0 => 0), 4 => Array(1 => 1, problem_id => 5, 0 => 0), 5 => Array(1 => 1, problem_id => 6, 0 => 0), 6 => Array(1 => 1, problem_id => 7, 0 => 0), 7 => Array(1 => 1, problem_id => 8, 0 => 0), 8 => Array(1 => 1, problem_id => 9, 0 => 0), 9 => Array(1 => 1, problem_id => 10, 0 => 0)) given). [] []
[2018-01-10 17:57:09] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #1 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #2 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #8 {main} [] []
[2018-01-10 17:57:09] application.DEBUG: < 500 [] []
[2018-01-10 17:58:30] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 17:58:30] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 17:58:30] application.CRITICAL: LogicException: The controller must return a response (Array(0 => Array(1 => 1, problem_id => 1, 0 => 0), 1 => Array(1 => 1, problem_id => 2, 0 => 0), 2 => Array(1 => 1, problem_id => 3, 0 => 0), 3 => Array(1 => 1, problem_id => 4, 0 => 0), 4 => Array(1 => 1, problem_id => 5, 0 => 0), 5 => Array(1 => 1, problem_id => 6, 0 => 0), 6 => Array(1 => 1, problem_id => 7, 0 => 0), 7 => Array(1 => 1, problem_id => 8, 0 => 0), 8 => Array(1 => 1, problem_id => 9, 0 => 0), 9 => Array(1 => 1, problem_id => 10, 0 => 0)) given). (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/HttpKernel.php line 169 {"exception":"[object] (LogicException(code: 0): The controller must return a response (Array(0 => Array(1 => 1, problem_id => 1, 0 => 0), 1 => Array(1 => 1, problem_id => 2, 0 => 0), 2 => Array(1 => 1, problem_id => 3, 0 => 0), 3 => Array(1 => 1, problem_id => 4, 0 => 0), 4 => Array(1 => 1, problem_id => 5, 0 => 0), 5 => Array(1 => 1, problem_id => 6, 0 => 0), 6 => Array(1 => 1, problem_id => 7, 0 => 0), 7 => Array(1 => 1, problem_id => 8, 0 => 0), 8 => Array(1 => 1, problem_id => 9, 0 => 0), 9 => Array(1 => 1, problem_id => 10, 0 => 0)) given). at /var/www/html/vendor/symfony/http-kernel/HttpKernel.php:169)"} []
[2018-01-10 17:58:30] application.ERROR: The controller must return a response (Array(0 => Array(1 => 1, problem_id => 1, 0 => 0), 1 => Array(1 => 1, problem_id => 2, 0 => 0), 2 => Array(1 => 1, problem_id => 3, 0 => 0), 3 => Array(1 => 1, problem_id => 4, 0 => 0), 4 => Array(1 => 1, problem_id => 5, 0 => 0), 5 => Array(1 => 1, problem_id => 6, 0 => 0), 6 => Array(1 => 1, problem_id => 7, 0 => 0), 7 => Array(1 => 1, problem_id => 8, 0 => 0), 8 => Array(1 => 1, problem_id => 9, 0 => 0), 9 => Array(1 => 1, problem_id => 10, 0 => 0)) given). [] []
[2018-01-10 17:58:30] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #1 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #2 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #8 {main} [] []
[2018-01-10 17:58:30] application.DEBUG: < 500 [] []
[2018-01-10 18:00:10] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:00:10] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:00:10] application.DEBUG: < 200 [] []
[2018-01-10 18:01:22] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:01:22] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:01:22] application.DEBUG: < 200 [] []
[2018-01-10 18:02:29] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:02:29] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:02:29] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'INSERT INTO stack_problem (0, 1, 2, 3, 4, 5, 6, 7, 8, 9) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [{"student_id":"1","problem_id":"1","done":"0","correct":"0"}, {"student_id":"1","problem_id":"2","done":"0","correct":"0"}, {"student_id":"1","problem_id":"3","done":"0","correct":"0"}, {"student_id":"1","problem_id":"4","done":"0","correct":"0"}, {"student_id":"1","problem_id":"5","done":"0","correct":"0"}, {"student_id":"1","problem_id":"6","done":"0","correct":"0"}, {"student_id":"1","problem_id":"7","done":"0","correct":"0"}, {"student_id":"1","problem_id":"8","done":"0","correct":"0"}, {"student_id":"1","problem_id":"9","done":"0","correct":"0"}, {"student_id":"1","problem_id":"10","done":"0","correct":"0"}]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, 1, 2, 3, 4, 5, 6, 7, 8, 9) VALUES ('Array', 'Array', 'Array', 'Array', 'Array' at line 1 (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO stack_problem (0, 1, 2, 3, 4, 5, 6, 7, 8, 9) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [{\"student_id\":\"1\",\"problem_id\":\"1\",\"done\":\"0\",\"correct\":\"0\"}, {\"student_id\":\"1\",\"problem_id\":\"2\",\"done\":\"0\",\"correct\":\"0\"}, {\"student_id\":\"1\",\"problem_id\":\"3\",\"done\":\"0\",\"correct\":\"0\"}, {\"student_id\":\"1\",\"problem_id\":\"4\",\"done\":\"0\",\"correct\":\"0\"}, {\"student_id\":\"1\",\"problem_id\":\"5\",\"done\":\"0\",\"correct\":\"0\"}, {\"student_id\":\"1\",\"problem_id\":\"6\",\"done\":\"0\",\"correct\":\"0\"}, {\"student_id\":\"1\",\"problem_id\":\"7\",\"done\":\"0\",\"correct\":\"0\"}, {\"student_id\":\"1\",\"problem_id\":\"8\",\"done\":\"0\",\"correct\":\"0\"}, {\"student_id\":\"1\",\"problem_id\":\"9\",\"done\":\"0\",\"correct\":\"0\"}, {\"student_id\":\"1\",\"problem_id\":\"10\",\"done\":\"0\",\"correct\":\"0\"}]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, 1, 2, 3, 4, 5, 6, 7, 8, 9) VALUES ('Array', 'Array', 'Array', 'Array', 'Array' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, 1, 2, 3, 4, 5, 6, 7, 8, 9) VALUES ('Array', 'Array', 'Array', 'Array', 'Array' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, 1, 2, 3, 4, 5, 6, 7, 8, 9) VALUES ('Array', 'Array', 'Array', 'Array', 'Array' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-10 18:02:29] application.ERROR: An exception occurred while executing 'INSERT INTO stack_problem (0, 1, 2, 3, 4, 5, 6, 7, 8, 9) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [{"student_id":"1","problem_id":"1","done":"0","correct":"0"}, {"student_id":"1","problem_id":"2","done":"0","correct":"0"}, {"student_id":"1","problem_id":"3","done":"0","correct":"0"}, {"student_id":"1","problem_id":"4","done":"0","correct":"0"}, {"student_id":"1","problem_id":"5","done":"0","correct":"0"}, {"student_id":"1","problem_id":"6","done":"0","correct":"0"}, {"student_id":"1","problem_id":"7","done":"0","correct":"0"}, {"student_id":"1","problem_id":"8","done":"0","correct":"0"}, {"student_id":"1","problem_id":"9","done":"0","correct":"0"}, {"student_id":"1","problem_id":"10","done":"0","correct":"0"}]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, 1, 2, 3, 4, 5, 6, 7, 8, 9) VALUES ('Array', 'Array', 'Array', 'Array', 'Array' at line 1 [] []
[2018-01-10 18:02:29] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO sta...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sta...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(83): Doctrine\DBAL\Connection->insert('stack_problem', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(35): App\Services\StackProblemsService->createStack(Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->initialize(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2018-01-10 18:02:29] application.DEBUG: < 500 [] []
[2018-01-10 18:05:57] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:05:57] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:05:58] application.DEBUG: < 200 [] []
[2018-01-10 18:30:40] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:30:40] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:30:40] application.DEBUG: < 200 [] []
[2018-01-10 18:32:08] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:32:08] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:32:08] application.DEBUG: < 200 [] []
[2018-01-10 18:32:30] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:32:30] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:32:30] application.DEBUG: < 200 [] []
[2018-01-10 18:33:57] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:33:57] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:33:57] application.DEBUG: < 200 [] []
[2018-01-10 18:33:58] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:33:58] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:33:58] application.DEBUG: < 200 [] []
[2018-01-10 18:34:32] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:34:32] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:34:58] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:34:58] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:35:37] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:35:37] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:35:37] application.DEBUG: < 200 [] []
[2018-01-10 18:36:21] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:36:21] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:36:21] application.DEBUG: < 200 [] []
[2018-01-10 18:37:12] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:37:12] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:37:12] application.DEBUG: < 200 [] []
[2018-01-10 18:37:15] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:37:15] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:37:15] application.DEBUG: < 200 [] []
[2018-01-10 18:37:25] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:37:25] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:37:25] application.DEBUG: < 200 [] []
[2018-01-10 18:37:55] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:37:55] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:37:55] application.DEBUG: < 200 [] []
[2018-01-10 18:38:04] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:38:04] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:38:04] application.DEBUG: < 200 [] []
[2018-01-10 18:38:14] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:38:14] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:38:14] application.DEBUG: < 200 [] []
[2018-01-10 18:38:19] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:38:19] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:38:19] application.DEBUG: < 200 [] []
[2018-01-10 18:38:21] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:38:21] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:38:21] application.DEBUG: < 200 [] []
[2018-01-10 18:38:22] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:38:22] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:38:22] application.DEBUG: < 200 [] []
[2018-01-10 18:38:23] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 18:38:23] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 18:38:23] application.DEBUG: < 200 [] []
[2018-01-10 21:12:50] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 21:12:50] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 21:12:50] application.DEBUG: < 200 [] []
[2018-01-10 21:19:43] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 21:19:43] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 21:19:43] application.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "1", "0", "0"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'student_id' in 'field list' (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params [\"1\", \"1\", \"0\", \"0\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'student_id' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'student_id' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'student_id' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-10 21:19:43] application.ERROR: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "1", "0", "0"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'student_id' in 'field list' [] []
[2018-01-10 21:19:43] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO sta...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sta...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(85): Doctrine\DBAL\Connection->insert('stack_problem', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(34): App\Services\StackProblemsService->createStack(Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->initialize(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2018-01-10 21:19:43] application.DEBUG: < 500 [] []
[2018-01-10 21:47:24] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 21:47:24] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 21:47:24] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "1", "0", "0"]:  SQLSTATE[HY000]: General error: 1364 Field 'stack_problem_id' doesn't have a default value (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params [\"1\", \"1\", \"0\", \"0\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'stack_problem_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'stack_problem_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'stack_problem_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-10 21:47:24] application.ERROR: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "1", "0", "0"]:  SQLSTATE[HY000]: General error: 1364 Field 'stack_problem_id' doesn't have a default value [] []
[2018-01-10 21:47:24] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO sta...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sta...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(85): Doctrine\DBAL\Connection->insert('stack_problem', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(34): App\Services\StackProblemsService->createStack(Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->initialize(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2018-01-10 21:47:24] application.DEBUG: < 500 [] []
[2018-01-10 21:47:40] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 21:47:40] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 21:47:40] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "1", "0", "0"]:  SQLSTATE[HY000]: General error: 1364 Field 'stack_problem_id' doesn't have a default value (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params [\"1\", \"1\", \"0\", \"0\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'stack_problem_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'stack_problem_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'stack_problem_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-10 21:47:40] application.ERROR: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "1", "0", "0"]:  SQLSTATE[HY000]: General error: 1364 Field 'stack_problem_id' doesn't have a default value [] []
[2018-01-10 21:47:40] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO sta...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sta...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(85): Doctrine\DBAL\Connection->insert('stack_problem', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(34): App\Services\StackProblemsService->createStack(Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->initialize(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2018-01-10 21:47:40] application.DEBUG: < 500 [] []
[2018-01-10 21:48:46] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 21:48:46] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 21:48:46] application.CRITICAL: Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "1", "0", "0"]:  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`id4147366_vestapp`.`stack_problem`, CONSTRAINT `fk_stack_problem_student2` FOREIGN KEY (`student_id`) REFERENCES `student` (`student_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params [\"1\", \"1\", \"0\", \"0\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`id4147366_vestapp`.`stack_problem`, CONSTRAINT `fk_stack_problem_student2` FOREIGN KEY (`student_id`) REFERENCES `student` (`student_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`id4147366_vestapp`.`stack_problem`, CONSTRAINT `fk_stack_problem_student2` FOREIGN KEY (`student_id`) REFERENCES `student` (`student_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`id4147366_vestapp`.`stack_problem`, CONSTRAINT `fk_stack_problem_student2` FOREIGN KEY (`student_id`) REFERENCES `student` (`student_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-10 21:48:46] application.ERROR: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "1", "0", "0"]:  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`id4147366_vestapp`.`stack_problem`, CONSTRAINT `fk_stack_problem_student2` FOREIGN KEY (`student_id`) REFERENCES `student` (`student_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) [] []
[2018-01-10 21:48:46] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO sta...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sta...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(85): Doctrine\DBAL\Connection->insert('stack_problem', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(34): App\Services\StackProblemsService->createStack(Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->initialize(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2018-01-10 21:48:46] application.DEBUG: < 500 [] []
[2018-01-10 21:52:20] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 21:52:20] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 21:52:20] application.DEBUG: < 200 [] []
[2018-01-10 21:52:25] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-10 21:52:25] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-10 21:52:25] application.DEBUG: < 200 [] []
