[2018-01-08 17:12:17] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:12:17] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:12:17] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-08 17:12:17] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-08 17:12:17] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-08 17:12:17] application.DEBUG: < 500 [] []
[2018-01-08 17:26:03] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:26:03] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:26:03] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-01-08 17:26:03] application.ERROR: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) [] []
[2018-01-08 17:26:03] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'kawamura', Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM s...', Array, Array) #5 /var/www/html/src/App/Services/SubjectsService.php(21): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM s...') #6 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Services\SubjectsService->getAll() #7 [internal function]: App\Controllers\SubjectsController->getAll() #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2018-01-08 17:26:03] application.DEBUG: < 500 [] []
[2018-01-08 17:26:07] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:26:07] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:26:07] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-01-08 17:26:07] application.ERROR: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) [] []
[2018-01-08 17:26:07] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'kawamura', Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM s...', Array, Array) #5 /var/www/html/src/App/Services/SubjectsService.php(21): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM s...') #6 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Services\SubjectsService->getAll() #7 [internal function]: App\Controllers\SubjectsController->getAll() #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2018-01-08 17:26:07] application.DEBUG: < 500 [] []
[2018-01-08 17:27:27] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:27:27] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:27:27] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-08 17:27:27] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-08 17:27:27] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-08 17:27:27] application.DEBUG: < 500 [] []
[2018-01-08 17:27:59] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics","route_parameters":{"_controller":"topics.controller:getAll","_route":"GET_api_v1_topics"},"request_uri":"http://localhost:9001/api/v1/topics","method":"GET"} []
[2018-01-08 17:27:59] application.DEBUG: > GET /api/v1/topics [] []
[2018-01-08 17:27:59] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-08 17:27:59] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-08 17:27:59] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/TopicsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/TopicsController.php(23): App\Controllers\TopicsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\TopicsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-08 17:27:59] application.DEBUG: < 500 [] []
[2018-01-08 17:29:30] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:29:30] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:29:30] application.DEBUG: < 200 [] []
[2018-01-08 17:30:00] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:30:00] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:30:00] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-08 17:30:00] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-08 17:30:00] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-08 17:30:00] application.DEBUG: < 500 [] []
[2018-01-08 17:31:34] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:31:34] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:31:34] application.DEBUG: < 200 [] []
[2018-01-08 17:38:35] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:35] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:35] application.DEBUG: < 200 [] []
[2018-01-08 17:38:36] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:36] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:36] application.DEBUG: < 200 [] []
[2018-01-08 17:38:37] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:37] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:37] application.DEBUG: < 200 [] []
[2018-01-08 17:38:37] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:37] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:37] application.DEBUG: < 200 [] []
[2018-01-08 17:38:38] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:38] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:38] application.DEBUG: < 200 [] []
[2018-01-08 17:38:38] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:38] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:38] application.DEBUG: < 200 [] []
[2018-01-08 17:38:38] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:38] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:38] application.DEBUG: < 200 [] []
[2018-01-08 17:38:38] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:38] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:38] application.DEBUG: < 200 [] []
[2018-01-08 17:38:38] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:38] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:38] application.DEBUG: < 200 [] []
[2018-01-08 17:38:38] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:38] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:38] application.DEBUG: < 200 [] []
[2018-01-08 17:38:38] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:38] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:38] application.DEBUG: < 200 [] []
[2018-01-08 17:38:38] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:38] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:38] application.DEBUG: < 200 [] []
[2018-01-08 17:38:39] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:39] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:39] application.DEBUG: < 200 [] []
[2018-01-08 17:38:39] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:39] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:39] application.DEBUG: < 200 [] []
[2018-01-08 17:38:39] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:39] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:39] application.DEBUG: < 200 [] []
[2018-01-08 17:38:39] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:39] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:39] application.DEBUG: < 200 [] []
[2018-01-08 17:38:39] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:39] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:39] application.DEBUG: < 200 [] []
[2018-01-08 17:38:40] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:40] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:40] application.DEBUG: < 200 [] []
[2018-01-08 17:38:40] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:40] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:40] application.DEBUG: < 200 [] []
[2018-01-08 17:38:40] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:40] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:40] application.DEBUG: < 200 [] []
[2018-01-08 17:38:41] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:38:41] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:38:41] application.DEBUG: < 200 [] []
[2018-01-08 17:39:51] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 17:39:51] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 17:39:51] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-08 17:39:51] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-08 17:39:51] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-08 17:39:51] application.DEBUG: < 500 [] []
[2018-01-08 20:02:27] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-08 20:02:27] application.ERROR: No route found for "GET /api/v1" [] []
[2018-01-08 20:02:27] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-08 20:02:27] application.DEBUG: < 404 [] []
[2018-01-08 20:02:33] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 20:02:33] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 20:02:34] application.CRITICAL: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 146 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:146)"} []
[2018-01-08 20:02:34] application.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] []
[2018-01-08 20:02:34] application.ERROR: #0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Symfony\Component\HttpFoundation\JsonResponse->setData(false) #1 /var/www/html/src/App/Controllers/SubjectsController.php(53): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array) #2 /var/www/html/src/App/Controllers/SubjectsController.php(31): App\Controllers\SubjectsController->myJsonResponse(Array) #3 [internal function]: App\Controllers\SubjectsController->getAll() #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #13 {main} [] []
[2018-01-08 20:02:34] application.DEBUG: < 500 [] []
[2018-01-08 20:10:15] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 20:10:16] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 20:10:16] application.DEBUG: < 200 [] []
[2018-01-08 23:40:57] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-08 23:40:57] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-08 23:40:58] application.DEBUG: < 200 [] []
[2018-01-08 23:41:05] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problemas" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problemas\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problemas\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-08 23:41:05] application.ERROR: No route found for "GET /api/v1/problemas" [] []
[2018-01-08 23:41:05] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-08 23:41:05] application.DEBUG: < 404 [] []
[2018-01-08 23:41:08] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems","route_parameters":{"_controller":"problems.controller:getAll","_route":"GET_api_v1_problems"},"request_uri":"http://localhost:9001/api/v1/problems","method":"GET"} []
[2018-01-08 23:41:08] application.DEBUG: > GET /api/v1/problems [] []
[2018-01-08 23:41:08] application.DEBUG: < 200 [] []
